global:
  scrape_interval: 5s
  scrape_timeout: 4s
scrape_configs:
  - job_name: load-backend
    static_configs:
      - targets: ['host.docker.internal:18082']
  - job_name: load-postgres
    static_configs:
      - targets: ['climbhub-postgres-exporter:9187']
